/* Copyright 2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "gesture_api.h"
#include "action_layer.h"

/*******************************************************************************
 * Configuration
 ******************************************************************************/

#ifndef NUM_LAYERS
#    define NUM_LAYERS 8
#endif

#ifndef MAX_ACTIVE_BINDINGS
#    define MAX_ACTIVE_BINDINGS 16
#endif

/*******************************************************************************
 * Layer Definition Types
 ******************************************************************************/

typedef struct {
    uint16_t key_index;
    uint16_t keycode;
} sparse_entry_t;

/**
 * Dense layer: flat keycode array covering a contiguous range of key indices.
 * Suitable for physical matrix layers where every key has a mapping.
 * The map array is stored in PROGMEM.
 */
typedef struct {
    uint16_t       base_index;
    uint16_t       count;
    const uint16_t *map;       // PROGMEM: indexed by (event_id - base_index)
} dense_layer_t;

/**
 * Sparse layer: sorted array of (key_index, keycode) pairs.
 * Suitable for virtual key overrides where few keys have non-transparent
 * mappings on a given layer. The entries array is stored in PROGMEM.
 */
typedef struct {
    uint16_t             count;
    const sparse_entry_t *entries;  // PROGMEM
} sparse_layer_t;

typedef enum {
    LAYER_DENSE,
    LAYER_SPARSE,
} layer_type_t;

/**
 * A layer definition. Tagged union of dense or sparse format.
 * default_keycode applies to keys not explicitly mapped:
 *   KC_TRNS (default) = fall through to lower layers
 *   KC_NO             = block (unmapped keys do nothing)
 */
typedef struct {
    layer_type_t type;
    uint16_t     default_keycode;
    union {
        dense_layer_t  dense;
        sparse_layer_t sparse;
    };
} gesture_layer_t;

/*******************************************************************************
 * User-Provided Functions
 ******************************************************************************/

/**
 * Map a QMK matrix position to a dense key index (0..NUM_KEY_POSITIONS-1).
 * Called at pipeline entry and by the keymap introspection override.
 *
 * Provide your own implementation or use DEFINE_KEY_INDICES with a
 * generated gesture_layout.h to auto-generate this function.
 */
extern uint8_t gesture_key_index(keypos_t pos);

/*******************************************************************************
 * Key Index Macros
 ******************************************************************************/

/**
 * Helper macros for DEFINE_KEY_INDICES. Used as callbacks to
 * GESTURE_LAYOUT_CALL (generated by gen_gesture_layout.py).
 */
#define _KP_ENUM(name, r, c) name,
#define _KP_FORWARD(name, r, c) [(r) * MATRIX_COLS + (c)] = (name) + 1,
#define _KP_REVERSE(name, r, c) [name] = { .row = (r), .col = (c) },

/**
 * Define key index enum, forward lookup, reverse lookup, and
 * gesture_key_index from a GESTURE_LAYOUT_CALL-style layout macro.
 *
 * Requires gesture_layout.h (generated by gen_gesture_layout.py) which
 * provides GESTURE_LAYOUT_CALL and NUM_KEY_POSITIONS.
 *
 * Usage:
 *   DEFINE_KEY_INDICES(
 *       L_PINKY, L_RING, L_MIDDLE, L_INDEX,    R_INDEX, R_MIDDLE,
 *       ...
 *   );
 *
 * Generates:
 *   - enum with each name as a dense index (0, 1, 2, ...)
 *   - gesture_key_index() mapping (row, col) -> index
 *   - gesture_index_to_pos[] reverse lookup (index -> keypos_t)
 */
#define DEFINE_KEY_INDICES(...) \
    enum { GESTURE_LAYOUT_CALL(_KP_ENUM, __VA_ARGS__) }; \
    static const uint8_t PROGMEM _gesture_pos_to_index \
        [MATRIX_ROWS * MATRIX_COLS] = { \
        GESTURE_LAYOUT_CALL(_KP_FORWARD, __VA_ARGS__) \
    }; \
    static const keypos_t PROGMEM gesture_index_to_pos \
        [NUM_KEY_POSITIONS] = { \
        GESTURE_LAYOUT_CALL(_KP_REVERSE, __VA_ARGS__) \
    }; \
    uint8_t gesture_key_index(keypos_t pos) { \
        return pgm_read_byte( \
            &_gesture_pos_to_index[pos.row * MATRIX_COLS + pos.col]) - 1; \
    }

/*******************************************************************************
 * Layer Lookup Functions
 ******************************************************************************/

/**
 * Return the layer definition for the given event type and layer number.
 * May return NULL if the layer has no mapping for this event type
 * (treated as all-transparent).
 *
 * A weak default implementation is provided in layer.c that looks up
 * layers defined with DEFINE_DENSE_LAYER / DEFINE_SPARSE_LAYER in a
 * table indexed by [event_type][layer_id]. Override with a strong
 * definition for custom lookup logic.
 */
const gesture_layer_t *layer_get(event_type_t type, uint8_t layer_id);

/**
 * Return the total number of layers.
 *
 * Weak default returns NUM_LAYERS. Override for dynamic layer counts.
 */
uint8_t layer_count(void);

/*******************************************************************************
 * Layer Definition Macros
 ******************************************************************************/

#include "progmem.h"

/* Valid type names for DEFINE_DENSE_LAYER / DEFINE_SPARSE_LAYER.
 * A typo produces "undeclared identifier" at compile time. */
enum { _gl_valid_key, _gl_valid_gesture, _gl_valid_encoder };

#define _GL_CHECK_TYPE(type_name) \
    _Static_assert(_gl_valid_##type_name >= 0, \
        "invalid layer type name: must be key, gesture, or encoder")

/**
 * Weak extern declarations for all layer slots.
 * Undefined slots resolve to address 0 (NULL) at link time via weak linkage.
 */
#define _GL_ENTRY(id) \
    extern const gesture_layer_t _gl_key_##id __attribute__((weak)); \
    extern const gesture_layer_t _gl_gesture_##id __attribute__((weak)); \
    extern const gesture_layer_t _gl_encoder_##id __attribute__((weak));
#include "layer_slots.inc"
#undef _GL_ENTRY

/**
 * Define a dense layer for the default layer table.
 * Creates a PROGMEM keycode array and a gesture_layer_t with a standardized
 * name so the weak default layer_get can find it.
 *
 *   DEFINE_DENSE_LAYER(key, 0, KC_A, KC_B, KC_C, ...)
 *   DEFINE_DENSE_LAYER(key, 1, KC_1, KC_2, KC_TRNS, ...)
 */
#define DEFINE_DENSE_LAYER(type_name, id, ...) \
    _GL_CHECK_TYPE(type_name); \
    static const uint16_t PROGMEM _gl_##type_name##_##id##_map[] = { __VA_ARGS__ }; \
    const gesture_layer_t _gl_##type_name##_##id = { \
        .type = LAYER_DENSE, \
        .default_keycode = KC_TRNS, \
        .dense = { \
            .base_index = 0, \
            .count = sizeof(_gl_##type_name##_##id##_map) / sizeof(uint16_t), \
            .map = _gl_##type_name##_##id##_map, \
        }, \
    }

/**
 * Define a sparse layer for the default layer table.
 * Creates a PROGMEM sparse_entry_t array and a gesture_layer_t with a
 * standardized name so the weak default layer_get can find it.
 *
 *   DEFINE_SPARSE_LAYER(gesture, 0, {GE_HOLD_mo1, MO(1)}, {GE_HOLD_tg2, TG(2)})
 *   DEFINE_SPARSE_LAYER(key, 2, {0, KC_F1}, {1, KC_F2})
 */
#define DEFINE_SPARSE_LAYER(type_name, id, ...) \
    _GL_CHECK_TYPE(type_name); \
    static const sparse_entry_t PROGMEM _gl_##type_name##_##id##_entries[] = { __VA_ARGS__ }; \
    const gesture_layer_t _gl_##type_name##_##id = { \
        .type = LAYER_SPARSE, \
        .default_keycode = KC_TRNS, \
        .sparse = { \
            .count = sizeof(_gl_##type_name##_##id##_entries) / sizeof(sparse_entry_t), \
            .entries = _gl_##type_name##_##id##_entries, \
        }, \
    }
