/* Copyright 2026
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "gesture_api.h"
#include "action_layer.h"
#include "progmem.h"

/*******************************************************************************
 * Configuration
 ******************************************************************************/

#ifndef MAX_ACTIVE_BINDINGS
#    define MAX_ACTIVE_BINDINGS 16
#endif

/*******************************************************************************
 * Layer Definition Types
 ******************************************************************************/

typedef struct {
    uint16_t key_index;
    uint16_t keycode;
} sparse_entry_t;

/**
 * Dense layer: flat keycode array covering a contiguous range of key indices.
 * Suitable for physical matrix layers where every key has a mapping.
 * The map array is stored in PROGMEM.
 */
typedef struct {
    uint16_t       base_index;
    uint16_t       count;
    const uint16_t *map;       // PROGMEM: indexed by (event_id - base_index)
} dense_layer_t;

/**
 * Sparse layer: sorted array of (key_index, keycode) pairs.
 * Suitable for virtual key overrides where few keys have non-transparent
 * mappings on a given layer. The entries array is stored in PROGMEM.
 */
typedef struct {
    uint16_t             count;
    const sparse_entry_t *entries;  // PROGMEM
} sparse_layer_t;

typedef enum {
    LAYER_DENSE,
    LAYER_SPARSE,
} layer_type_t;

/**
 * A layer definition. Tagged union of dense or sparse format.
 * default_keycode applies to keys not explicitly mapped:
 *   KC_TRNS (default) = fall through to lower layers
 *   KC_NO             = block (unmapped keys do nothing)
 */
typedef struct {
    layer_type_t type;
    uint16_t     default_keycode;
    union {
        dense_layer_t  dense;
        sparse_layer_t sparse;
    };
} gesture_layer_t;

/**
 * Per-layer entry in the layer table. Each field is a pointer to a
 * gesture_layer_t (or NULL for no mapping of that event type).
 */
typedef struct {
    const gesture_layer_t *key;
    const gesture_layer_t *gesture;
    const gesture_layer_t *encoder;
} gesture_layer_entry_t;

/*******************************************************************************
 * User-Provided Functions
 ******************************************************************************/

/**
 * Map a QMK matrix position to a dense key index (0..NUM_KEY_POSITIONS-1).
 * Called at pipeline entry and by the keymap introspection override.
 *
 * Provide your own implementation or use DEFINE_KEY_INDICES with a
 * generated gesture_layout.h to auto-generate this function.
 */
extern uint8_t gesture_key_index(keypos_t pos);

/*******************************************************************************
 * Key Index Macros
 ******************************************************************************/

/**
 * Helper macros for DEFINE_KEY_INDICES. Used as callbacks to
 * GESTURE_LAYOUT_CALL (generated by gen_gesture_layout.py).
 */
#define _KP_ENUM(name, r, c) name,
#define _KP_FORWARD(name, r, c) [(r) * MATRIX_COLS + (c)] = (name) + 1,
#define _KP_REVERSE(name, r, c) [name] = { .row = (r), .col = (c) },

/**
 * Define key index enum, forward lookup, reverse lookup, and
 * gesture_key_index from a GESTURE_LAYOUT_CALL-style layout macro.
 *
 * Requires gesture_layout.h (generated by gen_gesture_layout.py) which
 * provides GESTURE_LAYOUT_CALL and NUM_KEY_POSITIONS.
 *
 * Usage:
 *   DEFINE_KEY_INDICES(
 *       L_PINKY, L_RING, L_MIDDLE, L_INDEX,    R_INDEX, R_MIDDLE,
 *       ...
 *   );
 *
 * Generates:
 *   - enum with each name as a dense index (0, 1, 2, ...)
 *   - gesture_key_index() mapping (row, col) -> index
 *   - gesture_index_to_pos[] reverse lookup (index -> keypos_t)
 */
#define DEFINE_KEY_INDICES(...) \
    enum { GESTURE_LAYOUT_CALL(_KP_ENUM, __VA_ARGS__) }; \
    static const uint8_t PROGMEM _gesture_pos_to_index \
        [MATRIX_ROWS * MATRIX_COLS] = { \
        GESTURE_LAYOUT_CALL(_KP_FORWARD, __VA_ARGS__) \
    }; \
    static const keypos_t PROGMEM gesture_index_to_pos \
        [NUM_KEY_POSITIONS] = { \
        GESTURE_LAYOUT_CALL(_KP_REVERSE, __VA_ARGS__) \
    }; \
    uint8_t gesture_key_index(keypos_t pos) { \
        return pgm_read_byte( \
            &_gesture_pos_to_index[pos.row * MATRIX_COLS + pos.col]) - 1; \
    }

/*******************************************************************************
 * Layer Lookup Functions
 ******************************************************************************/

/**
 * Return the layer definition for the given event type and layer number.
 * May return NULL if the layer has no mapping for this event type
 * (treated as all-transparent).
 *
 * Default provided by DEFINE_LAYER_TABLE. Override with a strong
 * definition for custom lookup logic.
 */
const gesture_layer_t *layer_get(event_type_t type, uint8_t layer_id);

/**
 * Return the total number of layers.
 *
 * Default provided by DEFINE_LAYER_TABLE. Override for dynamic layer counts.
 */
uint8_t layer_count(void);

/*******************************************************************************
 * Layer Definition Macros
 ******************************************************************************/

/**
 * Define a dense layer. Creates a static gesture_layer_t with the given name.
 *
 *   DEFINE_DENSE_LAYER(base_keys, KC_A, KC_B, KC_C, ...)
 *   DEFINE_DENSE_LAYER(nav_keys, KC_LEFT, KC_DOWN, KC_UP, ...)
 */
#define DEFINE_DENSE_LAYER(name, ...) \
    static const uint16_t PROGMEM _gl_##name##_map[] = { __VA_ARGS__ }; \
    static const gesture_layer_t name = { \
        .type = LAYER_DENSE, \
        .default_keycode = KC_TRNS, \
        .dense = { \
            .base_index = 0, \
            .count = sizeof(_gl_##name##_map) / sizeof(uint16_t), \
            .map = _gl_##name##_map, \
        }, \
    }

/**
 * Define a sparse layer. Creates a static gesture_layer_t with the given name.
 *
 *   DEFINE_SPARSE_LAYER(base_gestures, {GE_HOLD_mo1, MO(1)}, {GE_HOLD_tg2, TG(2)})
 *   DEFINE_SPARSE_LAYER(nav_keys, {0, KC_LEFT}, {1, KC_DOWN})
 */
#define DEFINE_SPARSE_LAYER(name, ...) \
    static const sparse_entry_t PROGMEM _gl_##name##_entries[] = { __VA_ARGS__ }; \
    static const gesture_layer_t name = { \
        .type = LAYER_SPARSE, \
        .default_keycode = KC_TRNS, \
        .sparse = { \
            .count = sizeof(_gl_##name##_entries) / sizeof(sparse_entry_t), \
            .entries = _gl_##name##_entries, \
        }, \
    }

/**
 * Define the layer table and provide layer_get / layer_count.
 * Layer indices can be enum values or integer constants.
 *
 * Usage:
 *   DEFINE_LAYER_TABLE(
 *       [BASE] = { .key = &base_keys, .gesture = &base_gestures },
 *       [NAV]  = { .key = &nav_keys },
 *   );
 *
 * Unmentioned event types default to NULL (all-transparent).
 * Unmentioned layer indices are all-transparent.
 */
#define DEFINE_LAYER_TABLE(...) \
    static const gesture_layer_entry_t _gl_table[] = { __VA_ARGS__ }; \
    const gesture_layer_t *layer_get(event_type_t type, uint8_t layer_id) { \
        if (layer_id >= sizeof(_gl_table) / sizeof(gesture_layer_entry_t)) \
            return NULL; \
        const gesture_layer_entry_t *entry = &_gl_table[layer_id]; \
        switch (type) { \
            case EVENT_TYPE_KEY:     return entry->key; \
            case EVENT_TYPE_GESTURE: return entry->gesture; \
            case EVENT_TYPE_ENCODER: return entry->encoder; \
            default:                return NULL; \
        } \
    } \
    uint8_t layer_count(void) { \
        return sizeof(_gl_table) / sizeof(gesture_layer_entry_t); \
    }
