GESTURES_MODULE_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

SRC += $(GESTURES_MODULE_DIR)coordinator.c
SRC += $(GESTURES_MODULE_DIR)combo.c
SRC += $(GESTURES_MODULE_DIR)tapdance.c
SRC += $(GESTURES_MODULE_DIR)precog.c
SRC += $(GESTURES_MODULE_DIR)layer.c
